a = [ "a", "b", "c", "d" ]
a.rotate!        #=> ["b", "c", "d", "a"]
p a                #=> ["b", "c", "d", "a"]
p a.rotate!(2)     #=> ["d", "a", "b", "c"]
p a.rotate!(-3)    #=> ["a", "b", "c", "d"]